@AsyncPdfProcessor.Api_HostAddress = http://localhost:5122
@referenceNo =123e4567-e89b-12d3-a456-426614174000
@exchangeRateDate =2025-11-02

// GET /api/reports/{referenceNo}/status
GET {{AsyncPdfProcessor.Api_HostAddress}}/api/reports/{{referenceNo}}/status

###

// POST /api/reports -> Queue a report generation
POST {{AsyncPdfProcessor.Api_HostAddress}}/api/reports
Content-Type: application/json

{
 "exchangeRateDate": "{{exchangeRateDate}}"
}

###
