@AsyncPdfProcessor.Api_HostAddress = http://localhost:5122
@referenceNo =123e4567-e89b-12d3-a456-426614174000

// GET /api/reports/{referenceNo}/status
GET {{AsyncPdfProcessor.Api_HostAddress}}/api/reports/{{referenceNo}}/status

###
